#!/usr/bin/env python3
"""
scripts/calibrate_dual_bandpass.py
----------------------------------
Bench spectral cross-talk response calibration procedure for assembled
Waveshare IMX219-77IR + MidOpt DB660/850 camera on Jetson Nano.

Prompt 3 Section D2:
  - Once the IR-cut filter is absent, Bayer filters leak NIR across silicon.
  - The assembled camera must be placed before reference monochromatic or narrow-band
    optical sources (660nm Red and 850nm NIR) to measure the raw cross-talk matrix K:
        [DN_Red ]   [ k_RR   k_RNIR ]   [ L_660 ]
        [       ] = [               ] * [       ]
        [DN_Blue]   [ k_BR   k_BNIR ]   [ L_850 ]
  - The script inverts K to obtain K^-1, verifies stability, and exports the JSON
    calibration artifact used by core/ndvi.py.

Usage:
  python scripts/calibrate_dual_bandpass.py --help
  python scripts/calibrate_dual_bandpass.py --mock --output configs/db660_850_calibration.json
"""
import sys
import os
import argparse
import json
import numpy as np


def compute_unmixing_matrix(dn_660_source: np.ndarray,
                            dn_850_source: np.ndarray) -> np.ndarray:
    """
    Compute the 2x2 unmixing matrix K^-1 from two narrowband illumination tests:
      1. Pure 660nm source at unit radiance: yields [k_RR, k_BR]^T
      2. Pure 850nm source at unit radiance: yields [k_RNIR, k_BNIR]^T

    Parameters:
      dn_660_source: Observed [DN_Red, DN_Blue] when illuminated by pure 660nm.
      dn_850_source: Observed [DN_Red, DN_Blue] when illuminated by pure 850nm.

    Returns:
      2x2 unmixing matrix K^-1.
    """
    k_rr, k_br = float(dn_660_source[0]), float(dn_660_source[1])
    k_rnir, k_bnir = float(dn_850_source[0]), float(dn_850_source[1])

    k_matrix = np.array([
        [k_rr, k_rnir],
        [k_br, k_bnir]
    ], dtype=np.float32)

    det = np.linalg.det(k_matrix)
    if abs(det) < 1e-6:
        raise ValueError(f"Singular cross-talk matrix K (det={det:.6f}); cannot invert.")

    k_inv = np.linalg.inv(k_matrix)
    return k_inv


def main():
    parser = argparse.ArgumentParser(description="Bench spectral cross-talk calibration for IMX219-77IR + DB660/850.")
    parser.add_argument("--mock", action="store_true", help="Generate synthetic bench calibration matrix for verification.")
    parser.add_argument("--output", type=str, default="configs/db660_850_calibration.json", help="Path to save JSON calibration artifact.")
    parser.add_argument("--dn-660", nargs=2, type=float, default=[200.0, 10.0], help="Measured [DN_Red, DN_Blue] under pure 660nm reference source.")
    parser.add_argument("--dn-850", nargs=2, type=float, default=[40.0, 180.0], help="Measured [DN_Red, DN_Blue] under pure 850nm reference source.")
    args = parser.parse_args()

    dn_660 = np.array(args.dn_660, dtype=np.float32)
    dn_850 = np.array(args.dn_850, dtype=np.float32)

    print(f"Calibrating IMX219-77IR + DB660/850 from bench measurements:")
    print(f"  660nm illumination: DN_Red={dn_660[0]:.1f}, DN_Blue={dn_660[1]:.1f}")
    print(f"  850nm illumination: DN_Red={dn_850[0]:.1f}, DN_Blue={dn_850[1]:.1f}")

    k_inv = compute_unmixing_matrix(dn_660, dn_850)
    print(f"\nDerived 2x2 unmixing matrix K^-1:")
    print(k_inv)

    calib_payload = {
        "sensor": "Waveshare IMX219-77IR",
        "filter": "MidOpt DB660/850 Dual-Bandpass",
        "dn_660_response": dn_660.tolist(),
        "dn_850_response": dn_850.tolist(),
        "unmixing_matrix_2x2": k_inv.tolist(),
        "notes": "Generated by scripts/calibrate_dual_bandpass.py for core/ndvi.py"
    }

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as f:
        json.dump(calib_payload, f, indent=2)

    print(f"\nSaved calibration artifact to: {args.output}")


if __name__ == "__main__":
    main()
